name: Github Actions
on:
  push:
    branches: 
    - devlop
jobs:
  testbox:
    runs-on: ubuntu-latest
    steps:  
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: lakhan36899@gmail.com
        password: Lakhan@362
        subject: Github Actions job result
        body: Build joob completed ${{github.repository}} successfully!
        to: kawre36@gmail.com
        from: lakhan36899@gmail.com 
        content_type: text/html
